### ISSUE TITLE
failed to start with `ReferenceError: ReadableStream is not defined` exception

### ISSUE THREAD

**Issue by YukkuriC** [microsoft/vscode-vsce#1106]
installed by `npm install -g @vscode/vsce` as [this page](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce) says, then when I call `vsce` in cmd it returns error like this:
```
C:\Users\MSI\Desktop>vsce
C:\Users\MSI\AppData\Roaming\npm\node_modules\@vscode\vsce\node_modules\undici\lib\web\fetch\response.js:528
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (C:\Users\MSI\AppData\Roaming\npm\node_modules\@vscode\vsce\node_modules\undici\lib\web\fetch\response.js:528:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\MSI\AppData\Roaming\npm\node_modules\@vscode\vsce\node_modules\undici\lib\web\fetch\index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```
I'm using node `v16.16.0` and npm `8.11.0`

**Comment by Prathap-Thunga** [comment]
I encountered similar problem. Updating my Node.js version to the latest release resolved the issue.

**Comment by chandq** [comment]
`vsce --version
/Users/chendq/.nvm/versions/node/v16.16.0/lib/node_modules/@vscode/vsce/node_modules/undici/lib/web/fetch/response.js:528
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/Users/chendq/.nvm/versions/node/v16.16.0/lib/node_modules/@vscode/vsce/node_modules/undici/lib/web/fetch/response.js:528:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/chendq/.nvm/versions/node/v16.16.0/lib/node_modules/@vscode/vsce/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)`

I encountered similar problem. Updating my Node.js version to the v20.18.0 latest release resolved the issue. You can manage multiple Node version by nvm and .nvmrc file

**Comment by benibenj** [comment]
`vsce` requires at least `node` version `20`
