### ISSUE TITLE
"vsce package"output errors when I want to pack a .vsix file

### ISSUE THREAD

**Issue by LiarOnce** [Microsoft/vscode-vsce#154]
I followed the steps,but the error message is output and I can‘t find the **.vsix** file in the current directory.

```
vsce package
{ Error: Command failed: npm -v
ϵͳ�Ҳ���ָ����·����
ϵͳ�Ҳ���ָ����·����

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5) killed: false, code: 1, signal: null, cmd: 'npm -v' } Error: Command failed: npm -v
ϵͳ�Ҳ���ָ����·����
ϵͳ�Ҳ���ָ����·����
```

**Comment by joaomoreno** [comment]
Do you have `npm` installed?

**Comment by LiarOnce** [comment]
Yes.I do.

**Comment by joaomoreno** [comment]
If you run `npm -v` what comes out?

**Comment by LiarOnce** [comment]
I have been running `npm -v`,it prints the version.
The version number is `3.10.6`

**Comment by joaomoreno** [comment]
Closing as it seems to have been a setup error, got no more reports.
