### ISSUE TITLE
Error publishing - Exit Status 2

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode-vsce#163]
I'm trying to publish an update on my extension, but it keeps resulting **Exit status 2** on `prepublish` script. The problem seems related to a new dependency package (`chokidar`), because if I remove it, it works 😢 .

The other dependency on my extension is `walker` (no problem with that).

```
	"devDependencies": {
		"typescript": "^1.6.2",
		"vscode": "^0.11.x"
	},
	"dependencies": {
		"chokidar": "^1.6.1",
		"walker": "^1.0.7"
	}
```

I remember seeing somewhere that _in some cases, that I don't remember_, when a package has _its own dependencies_, I should add them to my `package.json` in order to `vsce` to work correctly. I tried that, but neither `npm install` works now, avoiding to install `fsevents` because of a `BADPLATFORM` (I'm using Windows OS btw). Is there any know problem/workaround, particularly with that package?

Thanks in advance

**Comment by alefragnani** [comment]
The `npm-debug.log` is here:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\alefr\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'vscode:prepublish' ]
2 info using npm@3.10.8
3 info using node@v6.10.2
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle project-manager@0.14.0~prevscode:prepublish: project-manager@0.14.0
6 silly lifecycle project-manager@0.14.0~prevscode:prepublish: no script for prevscode:prepublish, continuing
7 info lifecycle project-manager@0.14.0~vscode:prepublish: project-manager@0.14.0
8 verbose lifecycle project-manager@0.14.0~vscode:prepublish: unsafe-perm in lifecycle true
9 verbose lifecycle project-manager@0.14.0~vscode:prepublish: PATH: C:\Users\alefr\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\alefr\Documents\GitHub\vscode-project-manager\node_modules\.bin;C:\Program Files\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\ProgramData\Oracle\Java\javapath;C:\Windows\Microsoft.NET\Framework\v1.1.4322\;C:\Program Files\Borland\BDS\4.0\Bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Microsoft VS Code Insiders\bin;C:\Program Files\Skype\Phone\;C:\GNU\glo653wb\bin;C:\GNU\ctags58\ctags58;C:\Users\alefr\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\RemObjects Software\Elements\bin;C:\Program Files\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Inno Setup 5;C:\GNU\FPC\2.6.4\bin\i386-win32;C:\Program Files\nodejs\;C:\Users\alefr\Documents\Borland Studio Projects\Bpl;C:\Users\alefr\AppData\Local\atom\bin;C:\Users\alefr\AppData\Local\Microsoft\WindowsApps;C:\Users\alefr\AppData\Roaming\npm
10 verbose lifecycle project-manager@0.14.0~vscode:prepublish: CWD: C:\Users\alefr\Documents\GitHub\vscode-project-manager
11 silly lifecycle project-manager@0.14.0~vscode:prepublish: Args: [ '/d /s /c', 'node ./node_modules/vscode/bin/compile' ]
12 silly lifecycle project-manager@0.14.0~vscode:prepublish: Returned: code: 2  signal: null
13 info lifecycle project-manager@0.14.0~vscode:prepublish: Failed to exec vscode:prepublish script
14 verbose stack Error: project-manager@0.14.0 vscode:prepublish: `node ./node_modules/vscode/bin/compile`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\alefr\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\alefr\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid project-manager@0.14.0
16 verbose cwd C:\Users\alefr\Documents\GitHub\vscode-project-manager
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alefr\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "vscode:prepublish"
19 error node v6.10.2
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error project-manager@0.14.0 vscode:prepublish: `node ./node_modules/vscode/bin/compile`
22 error Exit status 2
23 error Failed at the project-manager@0.14.0 vscode:prepublish script 'node ./node_modules/vscode/bin/compile'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the project-manager package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./node_modules/vscode/bin/compile
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs project-manager
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls project-manager
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by joaomoreno** [comment]
Yes, you should list all your dependencies in `dependencies`. You should add `fsevents` to `optionalDependencies` since it is optional.

**Comment by alefragnani** [comment]
Hi @joaomoreno ,

Thanks for your suggestion. I tried to use `optionalDependencies`, but it didn't make any difference (same error) 😢 .

Sure you could take a look 👍 . The code is from a PR on my [Project Manager extension](https://github.com/alefragnani/vscode-project-manager/pull/107). You should look at the second commit, because I have asked the contributor to remove `chokidar` and use `fs.watchFile` instead, to avoid this publishing issue. On my test, I updated `package.json` using your suggestion:

```json
    "optionalDependencies": {
      "fsevents": "^1.0.0"
    },
    "dependencies": {
      "walker": "^1.0.7", // already used
      "chokidar": "^1.6.1", // here it is
      "anymatch": "^1.3.0", // from chokidar
      "async-each": "^1.0.0", // from chokidar
      "glob-parent": "^2.0.0", // from chokidar
      "inherits": "^2.0.1", // from chokidar
      "is-binary-path": "^1.0.0", // from chokidar
      "is-glob": "^2.0.0", // from chokidar
      "path-is-absolute": "^1.0.0", // from chokidar
      "readdirp": "^2.0.0" // from chokidar
  } 
```

When I run `npm install`, some warnings appears:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
```

Previously, the warnings were only from `node_modules\chokidar\node_modules\fsevents`

Since I found a workaround (use `fs.watchFile`), this issue is not blocking me anymore, but I would like to understand what is going on. If I'm doing something wrong, or there is some issue in the tooling.

Thanks for your help.

**Comment by joaomoreno** [comment]
@alefragnani I can't reproduce.

I cloned your repo, fetched @likun7981's branch, checked out commit `4727f1e4083d7690c6bda8d0c0d4b14c96fee899`, where he introduced `chokidar`, ran `git clean -xfd .` to have a fresh repo, ran `npm install` and then `vsce package`:

```
vscode-project-manager 4727f1e → vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> project-manager@0.13.5 vscode:prepublish /Users/joao/Desktop/vscode-project-manager
> node ./node_modules/vscode/bin/compile

Created: /Users/joao/Desktop/vscode-project-manager/project-manager-0.13.5.vsix
```

Everything succeeded.

**Comment by alefragnani** [comment]
> Created: /Users/joao/Desktop/vscode-project-manager/project-manager-0.13.5.vsix

@joaomoreno are you using MacOS?

The problem seems related to _Windows only_, since `fsevents` says `BADPLATFORM` for it 😢

**Comment by joaomoreno** [comment]
Tried it in Windows too:

![image](https://cloud.githubusercontent.com/assets/22350/24993553/2f0d8a72-2027-11e7-9254-42da5f7c00f3.png)

**Comment by eppz** [comment]
I have the same issue, more details at http://stackoverflow.com/questions/43503542/cant-publish-vs-code-extension-anymore-after-npm-update

**Please help,** I have valuable features to publish for user all around stuck into my MacBook. 😞
