### ISSUE TITLE
 vscode:prepublish: `tsc -p ./` keep throwing Exit status 2

### ISSUE THREAD

**Issue by eppz** [Microsoft/vscode-vsce#165]
I just can't publish my extension anymore.
It just worked fine before I ran `npm update`.

Now it says all day, no matter what:
```
    npm ERR! Darwin 15.6.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "vscode:prepublish"
    npm ERR! node v6.10.2
    npm ERR! npm  v3.10.10
    npm ERR! code ELIFECYCLE
    npm ERR! eppz-code@1.1.25 vscode:prepublish: `tsc -p ./`
    npm ERR! Exit status 2
    npm ERR! 
    npm ERR! Failed at the eppz-code@1.1.25 vscode:prepublish script 'tsc -p ./'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
```
See dependencies in [**`package.json`**](https://github.com/eppz/VSCode.Extension.eppz_Code/blob/master/package.json) to get the full picture. I tried with countless node versions (6.x to 7.x), no luck with any.

Please help, I have valuable features to publish for user all around stuck into my MacBook. 😞

**Comment by eppz** [comment]
Full npm-debug.log if that helps:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'vscode:prepublish' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle eppz-code@1.1.25~prevscode:prepublish: eppz-code@1.1.25
6 silly lifecycle eppz-code@1.1.25~prevscode:prepublish: no script for prevscode:prepublish, continuing
7 info lifecycle eppz-code@1.1.25~vscode:prepublish: eppz-code@1.1.25
8 verbose lifecycle eppz-code@1.1.25~vscode:prepublish: unsafe-perm in lifecycle true
9 verbose lifecycle eppz-code@1.1.25~vscode:prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/eppz/.vscode/extensions/eppz.eppz-code/node_modules/.bin:/Applications/MAMP/bin/php/php5.4.42/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/eppz/Developer/Android_SDK/tools:/Users/eppz/Developer/Android_SDK/platform-tools
10 verbose lifecycle eppz-code@1.1.25~vscode:prepublish: CWD: /Users/eppz/.vscode/extensions/eppz.eppz-code
11 silly lifecycle eppz-code@1.1.25~vscode:prepublish: Args: [ '-c', 'tsc -p ./' ]
12 silly lifecycle eppz-code@1.1.25~vscode:prepublish: Returned: code: 2  signal: null
13 info lifecycle eppz-code@1.1.25~vscode:prepublish: Failed to exec vscode:prepublish script
14 verbose stack Error: eppz-code@1.1.25 vscode:prepublish: `tsc -p ./`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid eppz-code@1.1.25
16 verbose cwd /Users/eppz/.vscode/extensions/eppz.eppz-code
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "vscode:prepublish"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error eppz-code@1.1.25 vscode:prepublish: `tsc -p ./`
22 error Exit status 2
23 error Failed at the eppz-code@1.1.25 vscode:prepublish script 'tsc -p ./'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the eppz-code package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc -p ./
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs eppz-code
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls eppz-code
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by eppz** [comment]
Manually (!) deleting entire `node_modules` content, then reinstall everything (with `npm install`) simply solved the issue.

**Comment by bsed** [comment]
```
kelvin@gnux:~/rls_vscode> vsce package
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rls-vscode@0.0.1 vscode:prepublish: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rls-vscode@0.0.1 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kelvin/.npm/_logs/2017-06-17T06_43_54_936Z-debug.log

```

**Comment by jlehrkind** [comment]
Manually (!) deleting entire `node_modules` **AND** `package-lock.json` content, then reinstall everything (with npm install) simply solved the issue.

**Comment by v-dantch** [comment]
Could you help to share more details about the solution? The node_module and package-lock,json are generated again after running 'npm install', then it goes into the loop.

**Comment by jamiesarahg** [comment]
Hi! I am having the same issue as both of the people above, however the suggested solution is not working. Is there any other issues that could be causing this?

I have attached my full log below:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'vscode:prepublish' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle pythonextensionforstudy@1.0.0~prevscode:prepublish: pythonextensionforstudy@1.0.0
6 info lifecycle pythonextensionforstudy@1.0.0~vscode:prepublish: pythonextensionforstudy@1.0.0
7 verbose lifecycle pythonextensionforstudy@1.0.0~vscode:prepublish: unsafe-perm in lifecycle true
8 verbose lifecycle pythonextensionforstudy@1.0.0~vscode:prepublish: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jamie/vscode-python/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle pythonextensionforstudy@1.0.0~vscode:prepublish: CWD: /Users/jamie/vscode-python
10 silly lifecycle pythonextensionforstudy@1.0.0~vscode:prepublish: Args: [ '-c', 'tsc -p ./' ]
11 silly lifecycle pythonextensionforstudy@1.0.0~vscode:prepublish: Returned: code: 2  signal: null
12 info lifecycle pythonextensionforstudy@1.0.0~vscode:prepublish: Failed to exec vscode:prepublish script
13 verbose stack Error: pythonextensionforstudy@1.0.0 vscode:prepublish: `tsc -p ./`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid pythonextensionforstudy@1.0.0
15 verbose cwd /Users/jamie/vscode-python
16 verbose Darwin 17.4.0
17 verbose argv "/usr/local/Cellar/node/9.8.0/bin/node" "/usr/local/bin/npm" "run" "vscode:prepublish"
18 verbose node v9.8.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error pythonextensionforstudy@1.0.0 vscode:prepublish: `tsc -p ./`
22 error Exit status 2
23 error Failed at the pythonextensionforstudy@1.0.0 vscode:prepublish script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
~                                                                                                      
~                                                                                                      
~                                      
```

**Comment by chausner** [comment]
`vsce package` fails for me with the exact same error as for @jamiesarahg. When I delete `node_modules` and `package-lock.json` and run `npm install`, `vsce package` fails with another error:

```
Executing prepublish script 'npm run vscode:prepublish'...
Error: stdout maxBuffer exceeded
```

**Comment by ziishaned** [comment]
The command will work if you remove the unused imports from typescript files.
