### ISSUE TITLE
'vsce package' error

### ISSUE THREAD

**Issue by baoyang2000** [Microsoft/vscode-vsce#190]
the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'vscode:prepublish' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle vscode-react-native@0.3.2~prevscode:prepublish: vscode-react-native@0.3.2
6 silly lifecycle vscode-react-native@0.3.2~prevscode:prepublish: no script for prevscode:prepublish, continuing
7 info lifecycle vscode-react-native@0.3.2~vscode:prepublish: vscode-react-native@0.3.2
8 verbose lifecycle vscode-react-native@0.3.2~vscode:prepublish: unsafe-perm in lifecycle true
9 verbose lifecycle vscode-react-native@0.3.2~vscode:prepublish: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/haizhi/vscode-react-native/node_modules/.bin:/usr/local/Cellar/node/7.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
10 verbose lifecycle vscode-react-native@0.3.2~vscode:prepublish: CWD: /Users/haizhi/vscode-react-native
11 silly lifecycle vscode-react-native@0.3.2~vscode:prepublish: Args: [ '-c', 'gulp' ]
12 silly lifecycle vscode-react-native@0.3.2~vscode:prepublish: Returned: code: 1  signal: null
13 info lifecycle vscode-react-native@0.3.2~vscode:prepublish: Failed to exec vscode:prepublish script
14 verbose stack Error: vscode-react-native@0.3.2 vscode:prepublish: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vscode-react-native@0.3.2
16 verbose cwd /Users/haizhi/vscode-react-native
17 error Darwin 16.5.0
18 error argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "run" "vscode:prepublish"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error vscode-react-native@0.3.2 vscode:prepublish: `gulp`
22 error Exit status 1
23 error Failed at the vscode-react-native@0.3.2 vscode:prepublish script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vscode-react-native package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vscode-react-native
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vscode-react-native
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by baoyang2000** [comment]
when I want package vscode-react-native(https://github.com/Microsoft/vscode-react-native),got the above error.

**Comment by joaomoreno** [comment]
https://github.com/Microsoft/vscode-react-native/blob/master/package.json#L248

You're missing the gulp task in the `vscode:prepublish` step.
