### ISSUE TITLE
`vsce publish` report `file data stream has unexpected number of bytes` error

### ISSUE THREAD

**Issue by zhaoyi0113** [Microsoft/vscode-vsce#276]
I got below error when I run `vsce publish -p xxx` command. I am using `node 8.9.4` `npm 6.2.0`.

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: file data stream has unexpected number of bytes
    at ByteCounter.<anonymous> (/Users/joeyzhao/.nvm/versions/node/v8.9.4/lib/node_modules/vsce/node_modules/yazl/index.js:144:99)
    at emitNone (events.js:111:20)
    at ByteCounter.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by zhaoyi0113** [comment]
You are right, it is a proxy issue. Thanks.
