### ISSUE TITLE
Error: Command failed: npm show vsce version

### ISSUE THREAD

**Issue by Revilotom** [microsoft/vscode-vsce#372]
I'm getting the following error when trying to package my extension:

```
$ npm show vsce version
1.64.0

$ vsce package
 ERROR  { Error: Command failed: npm show vsce version

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 243,
  signal: null,
  cmd: 'npm show vsce version' }
```

**Comment by joaomoreno** [comment]
Is there anything special about your system, that you can think of?

**Comment by Revilotom** [comment]
Do you mean like my OS?
```
$ uname -a 
Linux mai 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
Or like nodey things?
```
$ tsc --version
Version 3.5.2

$ npm --version
6.10.0

$ node --version
v10.14.2
```
Please give me more details on the information you require

**Comment by joaomoreno** [comment]
What does `which npm` return?

**Comment by Revilotom** [comment]
```
$ which npm
/usr/local/bin/npm
```

It does complete but it doesn't package the files properly, it should be more than 0..97kb.

```
$ vsce package
 ERROR  { Error: Command failed: npm show vsce version

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
  killed: false,
  code: 243,
  signal: null,
  cmd: 'npm show vsce version' }
 WARNING  A 'repository' field is missing from the 'package.json' manifest file.
Do you want to continue? [y/N] y
 DONE  Packaged: /home/tom/conjure/ide/conjure-0.0.1.vsix (2 files, 0.97KB)

```

**Comment by joaomoreno** [comment]
That is irrelevant to the error. You can see which files get packaged with `vsce ls`.

The error is related to vsce automatically checking for updates, which happens in the background. I'll simply not output any error if anything happens, since update checks are optional anyway.
