### ISSUE TITLE
running "vsce create-publisher <publisher>" fails (vsce -V => 0.9.0)

### ISSUE THREAD

**Issue by rcrosbourne** [Microsoft/vscode-vsce#50]
See error below
/usr/local/lib/node_modules/vsce/node_modules/denodeify/index.js:40
			return new Promise(promiseHandler);
			           ^
ReferenceError: Promise is not defined
    at /usr/local/lib/node_modules/vsce/node_modules/denodeify/index.js:40:15
    at Object.read (/usr/local/lib/node_modules/vsce/out/util.js:30:12)
    at Object.createPublisher (/usr/local/lib/node_modules/vsce/out/store.js:90:19)
    at Command.<anonymous> (/usr/local/lib/node_modules/vsce/out/main.js:51:73)
    at Command.listener (/usr/local/lib/node_modules/vsce/node_modules/commander/index.js:301:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/vsce/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/vsce/node_modules/commander/index.js:458:21)
    at module.exports (/usr/local/lib/node_modules/vsce/out/main.js:67:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/vsce/out/vsce:2:18)

**Comment by joaomoreno** [comment]
Which version of node do you have?

**Comment by rcrosbourne** [comment]
node --version (v0.10.24)

**Comment by joaomoreno** [comment]
`vsce` needs at least Node.js `0.12`. It is indicated in the `package.json`, so you should've gotten an error/warning by NPM when you installed it.
