### ISSUE TITLE
Installation: error Unexpected end of JSON input while parsing near '...E29Yl3o9WYezrgBI0tuFS'

### ISSUE THREAD

**Issue by agrawal-d** [microsoft/vscode-vsce#519]
I got this message:
`The latest version of vsce is 1.83.0 and you have 1.81.1.
Update it now: npm install -g vsce
`

So I ran `npm install -g vsce`

But I got the error:

```
npm ERR! Unexpected end of JSON input while parsing near '...E29Yl3o9WYezrgBI0tuFS'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/divyanshu/.npm/_logs/2020-12-20T19_17_45_388Z-debug.log
```

The entire log file is attached, and a truncated version is pasted here:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'vsce'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose npm-session 4f9d0899e0f3c69d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/vsce 2354ms
[...] truncated
218 silly resolveWithNewModule safe-buffer@5.2.1 checking installable status
219 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 423ms (from cache)
220 silly fetchPackageMetaData error for @types/node@* Unexpected end of JSON input while parsing near '...E29Yl3o9WYezrgBI0tuFS'
221 timing stage:rollbackFailedOptional Completed in 2ms
222 timing stage:runTopLevelLifecycles Completed in 15041ms
223 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...E29Yl3o9WYezrgBI0tuFS'
223 verbose stack     at JSON.parse (<anonymous>)
223 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
223 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
223 verbose stack     at runMicrotasks (<anonymous>)
223 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
224 verbose cwd /home/divyanshu/cph
225 verbose Linux 5.4.0-54-generic
226 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "vsce"
227 verbose node v12.18.3
228 verbose npm  v6.14.6
229 error Unexpected end of JSON input while parsing near '...E29Yl3o9WYezrgBI0tuFS'
230 verbose exit [ 1, true ]
```

[2020-12-20T19_17_45_388Z-debug.log](https://github.com/microsoft/vscode-vsce/files/5721394/2020-12-20T19_17_45_388Z-debug.log)

**Comment by joaomoreno** [comment]
Do you still get this error?

**Comment by agrawal-d** [comment]
No, I no longer get this error.
