### ISSUE TITLE
VSCE dependencies appear to be broken upstream

### ISSUE THREAD

**Issue by m-hilgendorf** [microsoft/vscode-vsce#520]
I'm not sure when this issue began. 

I run vsce on github actions to package an extension. It's installed with: 

```
npm install -g vsce
```

On Linux, running `vsce package` fails with:

```
 internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module '/usr/local/lib/node_modules/vsce/node_modules/cheerio-select/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vsce/node_modules/cheerio/lib/static.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/usr/local/lib/node_modules/vsce/node_modules/cheerio-select/package.json',
  requestPath: 'cheerio-select'
}
```

I'm not using `cheerio` in my extension and I can't replicate this locally, best I can tell this is only coming from a fresh install of vsce (I don't want to break my local dev environment). It looks like this is a versioning issue, the cheerio devs pushed a release today.

**Comment by m-hilgendorf** [comment]
This appears to have been resolved, I'll close the issue.
