### ISSUE TITLE
vsce 1.88.0 throws error with cheerio package

### ISSUE THREAD

**Issue by bfitzpat** [microsoft/vscode-vsce#565]
Updated to latest vsce version and seeing the following when we do a `vsce package`.
Any suggestions?

``` master  npm install -g vsce

added 1 package, changed 25 packages, and audited 73 packages in 3s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
 bfitzpat@pop-os  ~/github/vscode-didact   master  vsce package
internal/modules/cjs/loader.js:330
      throw err;
      ^

Error: Cannot find module '/home/bfitzpat/.npm-global/lib/node_modules/vsce/node_modules/cheerio/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/bfitzpat/.npm-global/lib/node_modules/vsce/out/package.js:22:17)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/bfitzpat/.npm-global/lib/node_modules/vsce/node_modules/cheerio/package.json',
  requestPath: 'cheerio'
}
```

**Comment by bfitzpat** [comment]
Reverting to 1.87.1 we do not see the issue

**Comment by bfitzpat** [comment]
Duplicate of https://github.com/microsoft/vscode-vsce/issues/566
