### ISSUE TITLE
ERROR  npm failed with exit code 2, Error: Command failed: node_modules/.bin/vsce package --no-yarn

### ISSUE THREAD

**Issue by immanishbainsla** [microsoft/vscode-vsce#567]
Hi there, 
It was running fine yesterday eve, but since today morning it has been showing this error.
I have tried deleting package-lock.json and node_modules and then npm install as well but couldn't get past this error

TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'esnext', 'commonjs', 'amd', 'system', or 'umd'.
 ERROR  npm failed with exit code 2
Error: Command failed: node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at CodeUtil.packageExtension (/home/.../out/util/codeUtil.js:180:23)
    at ExTester.<anonymous> (/home/.../out/extester.js:77:27)
    at Generator.next (<anonymous>)
    at /home/.../out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/.../out/extester.js:14:12)
    at ExTester.installVsix (/home/.../out/extester.js:58:16)
    at ExTester.<anonymous> (/home/.../out/extester.js:112:24)

"--module" flag is already set to "commonjs"

**Comment by immanishbainsla** [comment]
solved now.
needed to add "test-resources" in tsconfig.json > "exclude"
