### ISSUE TITLE
npm workspaces

### ISSUE THREAD

**Issue by panayot-cankov** [microsoft/vscode-vsce#580]
I've just finished moving several VSCode extensions into single monorepo using [npm v7 workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces).

However when the `vsce` packages using `npm` (not `yarn`) it does internally:
```
npm list --production --depth=99999 --loglevel=error
```
And that command fails from the workspace to lookup common modules in the root.
[I logged an issue at npm](https://github.com/npm/cli/issues/3378)
Although I am not sure if this is `npm list` bug or feature, probably the `npm list` will have to be extended to look those modules and then maybe some additional work will be necessary in the `vsce` to package the files correctly.

**Comment by Jolg42** [comment]
Got into this problem as well, the error was not obvious at all. See:
```
 ERROR  invalid relative path: extension/../../.eslintignore
npm ERR! Lifecycle script `package` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: package@31.0.3 
npm ERR!   at location: /home/runner/work/repo/repo/packages/vscode 
```

The error message here seems to be from the zipping library yazl, https://github.com/thejoshwolfe/yazl/blob/36b2a6a31a32637dca19b34e7b3295378e78a644/index.js#L368
 
The `npm list` call can be fount at https://github.com/microsoft/vscode-vsce/blob/main/src/npm.ts#L68

If there were more debug logs, it would have been easier to find out 😓

**Comment by 51ngul4r1ty** [comment]
Any progress on this?  I would also like to get VS Code Extensions working in a monorepo and it doesn't work for me.  I'm assuming that there's still work needed to fully support npm workspaces?

**Comment by xt0rted** [comment]
I just ran into this after a few hours of cryptic error messages. I haven't done extensive testing yet but my workaround so far is to bundle with [`@vercel/ncc`](https://github.com/vercel/ncc) just like I do on my GitHub Actions and then package with `vsce package --no-dependencies`. Since ncc bundles your code and your dependencies into a single file the `--no-dependencies` flag seems to be a sufficient hack.

**Comment by remcohaszing** [comment]
I ran into this issue too. But I figured out it's also possble to specify `vsce` options in `package.json`.

```jsonc
{
  // …
  "vsce": {
    "dependencies": false
  }
}
```

**Comment by vritant24** [comment]
Just ran into this issue, it would great to have this documented.
@remcohaszing 's workaround fixed it for us

**Comment by qarlosalberto** [comment]
any example?

**Comment by remcohaszing** [comment]
https://github.com/mdx-js/mdx-analyzer/blob/v1.3.0/packages/vscode-mdx/package.json#L38..L40

**Comment by qarlosalberto** [comment]
Thanks! But an example not using bundle. I cant use a webpack because I have external binaries.

**Comment by remcohaszing** [comment]
I found a workaround that allows you to partially include `node_modules`: https://github.com/mdx-js/mdx-analyzer/pull/371/commits/ccb7571ba2239b7f499c58439f83b1645e99d019

**Comment by deribaucourt** [comment]
In my case, with vsce 3.1.0, I get this error because there is a workspace in my package.json that is a link to a shared folder.
```
Error: not a file: /home/deribaucourt/Workspace/yocto-vscode/vscode-bitbake/server/node_modules/vscode-bitbake-lib
    at /home/deribaucourt/Workspace/yocto-vscode/vscode-bitbake/node_modules/yazl/index.js:31:79
    at FSReqCallback.oncomplete (node:fs:200:5)
```
The workaround doesn't seem to solve it.

**Comment by regchiu** [comment]
I get this error when I update `@vscode/vsce` from  `2.26.0` to `3.2.1`. So I can't fix the security issue.

```sh
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: not a file: /Users/user/Desktop/my-vscode-project/node_modules/my-npm-workspaces
    at /Users/user/Desktop/my-vscode-project/node_modules/yazl/index.js:31:52
    at FSReqCallback.oncomplete (node:fs:200:5)
Emitted 'error' event on ZipFile instance at:
    at /Users/user/Desktop/my-vscode-project/node_modules/yazl/index.js:31:38
    at FSReqCallback.oncomplete (node:fs:200:5)
```

**Comment by R-Bower** [comment]
> I get this error when I update `@vscode/vsce` from `2.26.0` to `3.2.1`. So I can't fix the security issue.
> 
> node:events:491
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: not a file: /Users/user/Desktop/my-vscode-project/node_modules/my-npm-workspaces
>     at /Users/user/Desktop/my-vscode-project/node_modules/yazl/index.js:31:52
>     at FSReqCallback.oncomplete (node:fs:200:5)
> Emitted 'error' event on ZipFile instance at:
>     at /Users/user/Desktop/my-vscode-project/node_modules/yazl/index.js:31:38
>     at FSReqCallback.oncomplete (node:fs:200:5)

I'm seeing the same in a pnpm monorepo.  vsce@2.26.0 works.

**Comment by marcelocra** [comment]
I got an `ERROR  Failed to parse semver of @types/vscode` in a `pnpm` workspace with `catalog:`s, when creating a package:

    vsce package --no-dependencies

**Fixed** it using the actual version for that package (only):

```jsonc

    // ...
    "@types/mocha": "catalog:",
    "@types/node": "catalog:",
    "@types/vscode": "1.92.0",
    "@vscode/test-cli": "catalog:",
    // ...

```

**Comment by realth000** [comment]
For pnpm + workspace, exclude all `node_modules` folders and run `--no-dependencies` works for me.

That is, add all `node_modules` in `.vscodeignore`

e.g.

```.gitignore
.vscode/**
.vscode-test/**
.gitignore
vsc-extension-quickstart.md


node_modules/**
lsp-server/node_modules/**
```

and run `vsce package --no-dependencies`
