### ISSUE TITLE
Versions after (i think) 1.80.0 break build of Prettier extension

### ISSUE THREAD

**Issue by ntotten** [microsoft/vscode-vsce#585]
When I build the prettier extension with vsce after 1.80.0 (or approximately). The build fails because it seems to not include the referenced prettier module. 

When the extension is loaded the following error happens:

```
[2021-06-22 17:25:29.844] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-06-22 17:25:29.845] [exthost] [error] Error: Cannot find module 'prettier'
Require stack:
- /Users/luisgregson/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
    at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
    at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
    at Object.2392 (/Users/luisgregson/.vscode/extensions/esbenp.prettier-vscode-8.0.0/external "util":1:26)
    at outputChannel (/Users/luisgregson/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:72851)
    at Object.9854 (/Users/luisgregson/.vscode/extensions/esbenp.prettier-vscode-8.0.0/src/LoggingService.ts:7:11)
    at r (/Users/luisgregson/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:72851)
    at /Users/luisgregson/.vscode/extensions/esbenp.prettier-vscode-8.0.0/src/extension.ts:9:1
    at /Users/luisgregson/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:74003
    at Object.<anonymous> (/Users/luisgregson/.vscode/extensions/esbenp.prettier-vscode-8.0.0/dist/extension.js:1:74024)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:27815)
    at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:24567)
    at Function.c._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:59196)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.t [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at m._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:25973)
    at m._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12617)
    at m._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11676)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

This doesn't reproduce in development mode, it only happens after bundling with vsce.

Reference issue: https://github.com/prettier/prettier-vscode/issues/2029

**Comment by joaomoreno** [comment]
Fix is: https://github.com/prettier/prettier-vscode/pull/2017
