### ISSUE TITLE
cannot find module graceful-readlink

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode-vsce#63]
Hi, 
When i try to make package for my extension by 
```vsce package```
i get the following error
```
C:\Users\skhan\Dropbox\code-project-manager>vsce package
module.js:328
    throw err;
    ^

Error: Cannot find module 'graceful-readlink'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\skhan\AppData\Roaming\npm\node_modules\vsce
node_modules\commander\index.js:7:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by joaomoreno** [comment]
Please try reinstalling `vsce` and let me know if that solves the issue.

**Comment by shanalikhan** [comment]
Thanks, solved
