### ISSUE TITLE
Error: libsecret-1.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by microhobby** [microsoft/vscode-vsce#645]
With the last update my pipelines has broken with the following error:

```
Error: libsecret-1.so.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1177:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vsce/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'ERR_DLOPEN_FAILED'
```

To reproduce:

```
docker run --rm -it node bash
npm install -g vsce
vsce --version
```

I can confirm that this not occurs on `1.102.0`

**Comment by microhobby** [comment]
Following the https://github.com/microsoft/vscode-vsce#usage-via-docker we have the same behavior:

```
internal/modules/cjs/loader.js:1057
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Error loading shared library libsecret-1.so.0: No such file or directory (needed by /opt/vsce/node_modules/keytar/build/Release/keytar.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/vsce/node_modules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```

**Comment by sourishkrout** [comment]
> Following the https://github.com/microsoft/vscode-vsce#usage-via-docker we have the same behavior:
> 
> ```
> internal/modules/cjs/loader.js:1057
>   return process.dlopen(module, path.toNamespacedPath(filename));
>                  ^
> 
> Error: Error loading shared library libsecret-1.so.0: No such file or directory (needed by /opt/vsce/node_modules/keytar/build/Release/keytar.node)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/opt/vsce/node_modules/keytar/lib/keytar.js:1:14)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> ```

Seeing the same issue which unfortunately is breaking my GitHub Actions.

**Comment by joaomoreno** [comment]
I assume you're all using `VSCE_PAT` for your build pipelines?

If so, I think all we have to do here is delay the loading of `keytar`.
