### ISSUE TITLE
vsce package doesn't work suddenly

### ISSUE THREAD

**Issue by taronlee** [microsoft/vscode-vsce#647]
Hello.

I don't know why this error happens suddenly..

```
Run vsce package -o lumos.vsix
/__w/_tool/node/10.24.1/x64/lib/node_modules/vsce/out/package.js:136
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/__w/_tool/node/10.24.1/x64/lib/node_modules/vsce/out/main.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Error: Process completed with exit code 1.
```

**Comment by thloke** [comment]
The latest version of vsce is only compatible from node.js version 14 onwards

https://github.com/microsoft/vscode-vsce/releases/tag/v2.0.0
