### ISSUE TITLE
When vsce package --no-yarn in CodeUtil.packageExtension is failing, tests are not launched and error is not reported

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode-vsce#649]
see https://app.circleci.com/pipelines/github/camel-tooling/vscode-camelk/1475/workflows/a28caad2-65f3-48a3-8367-225a9a90d0df/jobs/1802?invite=true#step-112-39

```
 ERROR  The following files have the same case insensitive path, which isn't supported by the VSIX format:
  - extension/LICENSE.txt
  - extension/LICENSE.txt
(node:37035) UnhandledPromiseRejectionWarning: Error: Command failed: node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at CodeUtil.packageExtension (/home/circleci/project/node_modules/vscode-extension-tester/out/util/codeUtil.js:190:23)
    at ExTester.<anonymous> (/home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:77:27)
    at Generator.next (<anonymous>)
    at /home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (/home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:58:16)
    at ExTester.<anonymous> (/home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:123:24)
```

**Comment by joaomoreno** [comment]
Irrelevant to the issue: why are you using `--no-yarn`?

**Comment by apupier** [comment]
omg, sorry I reported to the wrong tracker issue.

The problem i wanted to report is for vscode-extension-tester, opened https://github.com/redhat-developer/vscode-extension-tester/issues/388

> Irrelevant to the issue: why are you using --no-yarn?

would need to ask to vscode-extension-tester maintainer, based on history it was to implement this issue https://github.com/redhat-developer/vscode-extension-tester/issues/22

but well, I still need to investigate why it is failing with this strange error message complaining of 2 files with different cases but written with same case and for which I cannot find 2 of them in the repository. Maybe a problem in vsce but I wasn't able to reproduce outside of vscode-extension-tester so still investigating.
