### ISSUE TITLE
unexpected token ? in vsce/out/package.js:136

### ISSUE THREAD

**Issue by HotelCalifornia** [microsoft/vscode-vsce#653]
in an [azure CI pipeline build](https://dev.azure.com/purdue-acm-sigbots/VSCode%20Extension/_build/results?buildId=2769&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86) for our extension we get the following failure when trying to package it:

```
/opt/hostedtoolcache/node/10.24.1/x64/lib/node_modules/vsce/out/package.js:136
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/10.24.1/x64/lib/node_modules/vsce/out/main.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

not sure what's going on here

**Comment by HotelCalifornia** [comment]
never mind, needed to update to node 14

**Comment by VidarDev** [comment]
So i haev the same error on node 17 whats going wrong?

**Comment by VidarDev** [comment]
i have the same error with node 16

**Comment by xieyezi** [comment]
> i have the same error with node 16

Resovle it?

**Comment by melir91** [comment]
In my case I installed vsce with Node 12.x.x and then switched to Node 14.x.x

Installed vsce with Node 14.x.x and then the issue was resolved

**Comment by Rainy934** [comment]
> > i have the same error with node 16
> 
> Resovle it?

有解决方案吗？
