### ISSUE TITLE
Erroring out when try to publish via GitHub Actions

### ISSUE THREAD

**Issue by Power-Maverick** [microsoft/vscode-vsce#664]
I had configured GitHub Actions a few months back to publish the extension and was working fine but recently it has been failing.
I tried to change the PAT but had no luck. The same command with the same PAT works fine when doing it locally (_my local vsce version is `2.5.1` and GitHub Actions always downloads the latest available version_)

The error log is below:
```
/opt/hostedtoolcache/node/12.22.7/x64/lib/node_modules/vsce/out/package.js:136
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/12.22.7/x64/lib/node_modules/vsce/out/main.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Error: Process completed with exit code 1.
```

This is the [link](https://github.com/Power-Maverick/DataverseDevTools-VSCode/blob/main/.github/workflows/release.yml) to the GitHub Actions's workflow file.

**Comment by joaomoreno** [comment]
Starting with v2.0.0, vsce now depends on Node 14.
