### ISSUE TITLE
yazl throws unknown error during package

### ISSUE THREAD

**Issue by codegrue** [microsoft/vscode-vsce#680]
$ vsce package
Executing prepublish script 'npm run vscode:prepublish'...

> auto-translate-json@1.1.0 vscode:prepublish C:\Users\jeff\OneDrive\Projects\Code\VSCode Extensions\auto-translate-json
> npm run compile

> auto-translate-json@1.1.0 compile C:\Users\jeff\OneDrive\Projects\Code\VSCode Extensions\auto-translate-json
> tsc -p ./

This extension consists of 2405 files, out of which 1314 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: UNKNOWN: unknown error, read
Emitted 'error' event on ZipFile instance at:
    at ReadStream.<anonymous> (C:\Users\jeff\AppData\Roaming\npm\node_modules\vsce\node_modules\yazl\index.js:39:14)
    at ReadStream.emit (events.js:375:28)
    at internal/fs/streams.js:173:14
    at FSReqCallback.wrapper [as oncomplete] (fs.js:561:5) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'read'
}

**Comment by joaomoreno** [comment]
What version of vsce are you using? Can I take a look at the sources of your extension?

**Comment by codegrue** [comment]
Please. The source is here:

https://github.com/codegrue/auto-translate-json

**Comment by topce** [comment]
Hi @codegrue  
I change  in package.json 
"engines": {
    "vscode": "^1.63.1"
  },
  packaging works 
  I use same (latest )  version of vcse 

vsce --version
2.6.3

node --version
v16.13.1

@codegrue  what version of node you use ?

**Comment by joaomoreno** [comment]
I first got an entrypoint error, but after changing `main` to `./out/main.js` on `package.json`, everything worked just fine for me:

![image](https://user-images.githubusercontent.com/22350/148774730-54d455eb-284f-449c-814c-91d64548a5b3.png)

What Node.JS version are you on?

**Comment by codegrue** [comment]
Upgrading Node fixed the issue. Thank you.
