### ISSUE TITLE
Can't install vsce with nodejs/npm  

### ISSUE THREAD

**Issue by kraabrsg** [microsoft/vscode-vsce#695]
Hi, 

having setup the actual nodejsnpm package (lts version, zip file)

Set .npmrc (Users Folder) file with our proxy and certificate file:
![grafik](https://user-images.githubusercontent.com/86772851/152527042-ab9fe887-6fee-4982-b4f0-34af6c6d8893.png)

The npmnodejs folder is like the folder with the certificate, fully accessible.

Npm Version: 8.1.2
Node Version: V16.13.2

Getting this errors (npm install -g vsce)

```
npm ERR! code 1
npm ERR! path C:\fullpath\zowe_nodejsnpm\node_modules\vsce\node_modules\keytar
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || npm run build
npm ERR! > keytar@7.8.0 build
npm ERR! > node-gyp rebuild
npm ERR! prebuild-install WARN install unable to get local issuer certificate
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.7.8 found at "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\fullpath\zowe_nodejsnpm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\fullpath\zowe_nodejsnpm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\fullpath\zowe_nodejsnpm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\fullpath\zowe_nodejsnpm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\fullpath\zowe_nodejsnpm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\fullpath\zowe_nodejsnpm\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\fullpath\zowe_nodejsnpm\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\fullpath\\zowe_nodejsnpm\\node.exe" "C:\\fullpath\\zowe_nodejsnpm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\fullpath\zowe_nodejsnpm\node_modules\vsce\node_modules\keytar
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MYUSER\AppData\Local\npm-cache\_logs\2022-02-04T12_08_32_164Z-debug.log
```

OS: WIN 10 Enterprise / 10.0.19042 Build 19042

Is this releated to node ? Or is a prefix needed here?  Can this be fixed?

Thanks!

**Comment by kraabrsg** [comment]
Well finally found it:
https://github.com/nodejs/node-gyp/blob/master/docs/Updating-npm-bundled-node-gyp.md

after doing this the installation is working like expected (admin rights needed...)
