### ISSUE TITLE
vsce package fails with `SyntaxError: Unexpected token '?'`

### ISSUE THREAD

**Issue by roipoussiere** [microsoft/vscode-vsce#715]
```
yarn run vsce package
yarn run v1.22.18
$ /home/roipoussiere/projets/cadquery-vscode/node_modules/.bin/vsce package
/home/roipoussiere/projets/cadquery-vscode/node_modules/vsce/out/package.js:136
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/roipoussiere/projets/cadquery-vscode/node_modules/vsce/out/main.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Same error when I install vsce via `sudo npm install -g vsce`.

I'm on Ubuntu 21.10, yarn 1.22.18, node 12.22.5

**Comment by roipoussiere** [comment]
Ok, I upgraded node to the latest version and the problem is gone.
