### ISSUE TITLE
`vsce package`: `Error [ERR_REQUIRE_ESM]: require() of ES Module `

### ISSUE THREAD

**Issue by worksofliam** [microsoft/vscode-vsce#772]
This just started today.

```
> vsce package

/opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/node_modules/cheerio/lib/parsers/parse5-adapter.js:14
var parse5_1 = require("parse5");
               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/node_modules/parse5/dist/cjs/index.js from /opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/node_modules/cheerio/lib/parsers/parse5-adapter.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/node_modules/parse5/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/node_modules/cheerio/lib/parsers/parse5-adapter.js:14:16)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/node_modules/cheerio/lib/index.js:41:27)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/out/package.js:36:30)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/out/main.js:27:19)
    at Object.<anonymous> (/opt/hostedtoolcache/node/16.17.0/x64/lib/node_modules/vsce/vsce:2:1) {
  code: 'ERR_REQUIRE_ESM'
}
```

See full error and setup in my PR action: https://github.com/halcyon-tech/vscode-ibmi/runs/8160148320?check_suite_focus=true

**Comment by pgrivachev** [comment]
The same for me:
```
~/F/dbt-language-server►npx vsce@latest package -o e2e-test.vsix                                                  14.135s  (fix-vsce|?) 18:21
Need to install the following packages:
  vsce@2.11.0
Ok to proceed? (y) y
/Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/cheerio/lib/parsers/parse5-adapter.js:14
var parse5_1 = require("parse5");
               ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/parse5/dist/cjs/index.js from /Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/cheerio/lib/parsers/parse5-adapter.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/parse5/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/cheerio/lib/parsers/parse5-adapter.js:14:16)
    at Object.<anonymous> (/Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/cheerio/lib/index.js:41:27)
    at Object.<anonymous> (/Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/vsce/out/package.js:36:30)
    at Object.<anonymous> (/Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/vsce/out/main.js:27:19)
    at Object.<anonymous> (/Users/pavel/.npm/_npx/a3902b48c606636d/node_modules/vsce/vsce:2:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.4.0
```

**Comment by worksofliam** [comment]
Thanks for sharing as well @pgrivachev - hopefully this can be resolved fast.

**Comment by lukecotter** [comment]
I am also seeing this

**Comment by unwls** [comment]
Same issue here!

**Comment by rgrunber** [comment]
This may have been fixed a few minutes ago in https://github.com/inikulin/parse5/issues/663 (vsce -> cheerio -> parse5) . Re-installing vsce seemed to fix it for me.

**Comment by filiptronicek** [comment]
Not sure what causes this, tried changing Node versions, seems to happen on both Node 14 and 16. Downgrading to [2.10.0](https://www.npmjs.com/package/vsce/v/2.10.0) seems to not aid the issue.

On the contrary, I think this cannot be caused by a new version: this one has been out since the beginning of the week. It only happens for me on some machines, and seems to happen randomly.

**Comment by worksofliam** [comment]
@rgrunber Just re-ran my pipeline and it is working now. Thanks for posting!

**Comment by maoxiaoke** [comment]
@filiptronicek [parse5](https://github.com/inikulin/parse5/issues/663) made a break change.

**Comment by filiptronicek** [comment]
Running a new workspace in Gitpod seems to have fixed the issue for me! 🎉
